project:
  type: website
  output-dir: docs

website:
  title: "lizwebsite1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
      - href: posts/posts.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

